version: '3.6'
services:
  proxy:
    image: manolomon/crashify-proxy:latest
    command: /usr/local/bin/envoy -c /etc/envoy.yaml
    ports:
      - '8080:8080'
    network_mode: host

  server:
    image: deklok/crashify-server:latest
    command: bundle exec ruby servercontract.rb
    expose:
      - '14586'
    network_mode: host