# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crashify.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("crashify.proto", :syntax => :proto3) do
    add_message "crashify.Usuario" do
      optional :idUsuario, :int32, 1
      optional :nombre, :string, 2
      optional :rol, :int32, 3
      optional :usuario, :string, 4
      optional :password, :string, 5
    end
    add_message "crashify.Sesion" do
      optional :usuario, :string, 1
      optional :password, :string, 2
    end
    add_message "crashify.Empty" do
    end
    add_message "crashify.Mensaje" do
      optional :msg, :string, 1
    end
  end
end

module Crashify
  Usuario = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Usuario").msgclass
  Sesion = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Sesion").msgclass
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Empty").msgclass
  Mensaje = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Mensaje").msgclass
end
