# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: crashify.proto for package 'crashify'

require 'grpc'
require 'crashify_pb'

module Crashify
  module Transito
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'crashify.Transito'

      rpc :Ping, Mensaje, Mensaje
      rpc :IniciarSesion, Sesion, Usuario
      rpc :ObtenerUsuarios, ID, ListaUsuarios
      rpc :RegistrarUsuario, Usuario, Respuesta
      rpc :ActualizarUsuario, Usuario, Respuesta
      rpc :EliminarUsuario, ID, Respuesta
      rpc :ObtenerReportes, Mensaje, ListaReportes
      rpc :ObtenerDetalleReporte, ID, Reporte
      rpc :DictaminarReporte, Dictamen, Respuesta
      rpc :DictaminarReporteUnificado, DictamenUnificado, Respuesta
      rpc :UnificarReportes, ListaID, Respuesta
    end

    Stub = Service.rpc_stub_class
  end
end
