# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crashify.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("crashify.proto", :syntax => :proto3) do
    add_message "crashify.Usuario" do
      optional :idUsuario, :int32, 1
      optional :nombre, :string, 2
      optional :rol, :int32, 3
      optional :usuario, :string, 4
      optional :password, :string, 5
      optional :idSuperior, :int32, 6
    end
    add_message "crashify.ListaUsuarios" do
      repeated :usuarios, :message, 1, "crashify.Usuario"
    end
    add_message "crashify.Vehiculo" do
      optional :numPlacas, :string, 1
      optional :modelo, :string, 2
      optional :marca, :string, 3
      optional :year, :string, 4
      optional :color, :string, 5
      optional :numPoliza, :string, 6
      optional :aseguradora, :string, 7
    end
    add_message "crashify.Reporte" do
      optional :idReporte, :int32, 1
      optional :latitud, :float, 2
      optional :longitud, :float, 3
      optional :hora, :string, 4
      repeated :vehiculos, :message, 5, "crashify.Vehiculo"
      optional :idSiniestro, :int32, 6
      optional :estado, :int32, 7
    end
    add_message "crashify.Foto" do
      optional :foto, :bytes, 1
    end
    add_message "crashify.ReporteResumido" do
      optional :idReporte, :int32, 1
      optional :latitud, :float, 2
      optional :longitud, :float, 3
      optional :hora, :string, 4
      optional :idSiniestro, :int32, 5
      optional :estado, :int32, 6
      optional :nombreConductor, :string, 7
      optional :idSiniestroUnificado, :int32, 8
    end
    add_message "crashify.ListaReportes" do
      repeated :reportes, :message, 1, "crashify.ReporteResumido"
    end
    add_message "crashify.Dictamen" do
      optional :dictamen, :string, 1
      optional :hora, :string, 2
      optional :idUsuario, :int32, 3
      optional :idSiniestro, :int32, 4
      optional :idReporte, :int32, 5
    end
    add_message "crashify.DictamenUnificado" do
      optional :dictamen, :string, 1
      optional :hora, :string, 2
      optional :idUsuario, :int32, 3
      optional :idSiniestro, :int32, 4
      repeated :idReporte, :int32, 5
    end
    add_message "crashify.ID" do
      optional :identifier, :int32, 1
    end
    add_message "crashify.ListaID" do
      repeated :listaID, :int32, 1
    end
    add_message "crashify.Respuesta" do
      optional :code, :int32, 1
      optional :mensaje, :string, 2
    end
    add_message "crashify.Sesion" do
      optional :usuario, :string, 1
      optional :password, :string, 2
    end
    add_message "crashify.Empty" do
    end
    add_message "crashify.Mensaje" do
      optional :msg, :string, 1
    end
  end
end

module Crashify
  Usuario = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Usuario").msgclass
  ListaUsuarios = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.ListaUsuarios").msgclass
  Vehiculo = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Vehiculo").msgclass
  Reporte = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Reporte").msgclass
  Foto = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Foto").msgclass
  ReporteResumido = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.ReporteResumido").msgclass
  ListaReportes = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.ListaReportes").msgclass
  Dictamen = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Dictamen").msgclass
  DictamenUnificado = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.DictamenUnificado").msgclass
  ID = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.ID").msgclass
  ListaID = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.ListaID").msgclass
  Respuesta = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Respuesta").msgclass
  Sesion = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Sesion").msgclass
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Empty").msgclass
  Mensaje = Google::Protobuf::DescriptorPool.generated_pool.lookup("crashify.Mensaje").msgclass
end
