# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freeway.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("freeway.proto", :syntax => :proto3) do
    add_message "freeway.Usuario" do
      optional :idUsuario, :int32, 1
      optional :nombre, :string, 2
      optional :rol, :int32, 3
      optional :usuario, :string, 4
      optional :password, :string, 5
    end
    add_message "freeway.Sesion" do
      optional :usuario, :string, 1
      optional :password, :string, 2
    end
    add_message "freeway.Empty" do
    end
    add_message "freeway.Mensaje" do
      optional :msg, :string, 1
    end
  end
end

module Freeway
  Usuario = Google::Protobuf::DescriptorPool.generated_pool.lookup("freeway.Usuario").msgclass
  Sesion = Google::Protobuf::DescriptorPool.generated_pool.lookup("freeway.Sesion").msgclass
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("freeway.Empty").msgclass
  Mensaje = Google::Protobuf::DescriptorPool.generated_pool.lookup("freeway.Mensaje").msgclass
end
