#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'freway_types'

module DictaminarReporte
  class Client
    include ::Thrift::Client

    def dictaminarReporte(dictamen, idPerito, idReporte)
      send_dictaminarReporte(dictamen, idPerito, idReporte)
      return recv_dictaminarReporte()
    end

    def send_dictaminarReporte(dictamen, idPerito, idReporte)
      send_message('dictaminarReporte', DictaminarReporte_args, :dictamen => dictamen, :idPerito => idPerito, :idReporte => idReporte)
    end

    def recv_dictaminarReporte()
      result = receive_message(DictaminarReporte_result)
      return result.success unless result.success.nil?
      raise result.exp unless result.exp.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'dictaminarReporte failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_dictaminarReporte(seqid, iprot, oprot)
      args = read_args(iprot, DictaminarReporte_args)
      result = DictaminarReporte_result.new()
      begin
        result.success = @handler.dictaminarReporte(args.dictamen, args.idPerito, args.idReporte)
      rescue ::Error => exp
        result.exp = exp
      end
      write_result(result, oprot, 'dictaminarReporte', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class DictaminarReporte_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    DICTAMEN = 1
    IDPERITO = 2
    IDREPORTE = 3

    FIELDS = {
      DICTAMEN => {:type => ::Thrift::Types::STRUCT, :name => 'dictamen', :class => ::Dictamen},
      IDPERITO => {:type => ::Thrift::Types::I32, :name => 'idPerito'},
      IDREPORTE => {:type => ::Thrift::Types::I32, :name => 'idReporte'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class DictaminarReporte_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    EXP = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::Respuesta},
      EXP => {:type => ::Thrift::Types::STRUCT, :name => 'exp', :class => ::Error}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

