#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Dictamen; end

class Respuesta; end

class Reporte; end

class Usuario; end

class Vehiculo; end

class Error < ::Thrift::Exception; end

class Dictamen
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDDICTAMEN = 1
  COMENTARIO = 2
  FECHA = 3
  HORA = 4
  LADOCULPABLE = 5

  FIELDS = {
    IDDICTAMEN => {:type => ::Thrift::Types::I32, :name => 'idDictamen'},
    COMENTARIO => {:type => ::Thrift::Types::STRING, :name => 'comentario'},
    FECHA => {:type => ::Thrift::Types::STRING, :name => 'fecha'},
    HORA => {:type => ::Thrift::Types::STRING, :name => 'hora'},
    LADOCULPABLE => {:type => ::Thrift::Types::STRING, :name => 'ladoCulpable'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field idDictamen is unset!') unless @idDictamen
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field comentario is unset!') unless @comentario
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field fecha is unset!') unless @fecha
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field hora is unset!') unless @hora
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field ladoCulpable is unset!') unless @ladoCulpable
  end

  ::Thrift::Struct.generate_accessors self
end

class Respuesta
  include ::Thrift::Struct, ::Thrift::Struct_Union
  RESPUESTACODE = 1
  MENSAJE = 2

  FIELDS = {
    RESPUESTACODE => {:type => ::Thrift::Types::I32, :name => 'respuestaCode'},
    MENSAJE => {:type => ::Thrift::Types::STRING, :name => 'mensaje'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field respuestaCode is unset!') unless @respuestaCode
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field mensaje is unset!') unless @mensaje
  end

  ::Thrift::Struct.generate_accessors self
end

class Reporte
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDREPORTE = 1
  LATITUD = 2
  LONGITUD = 3
  ESTAUTS = 4
  LADOCULPABLE = 5
  IMPLICADOS = 6

  FIELDS = {
    IDREPORTE => {:type => ::Thrift::Types::I32, :name => 'idReporte'},
    LATITUD => {:type => ::Thrift::Types::STRING, :name => 'latitud'},
    LONGITUD => {:type => ::Thrift::Types::STRING, :name => 'longitud'},
    ESTAUTS => {:type => ::Thrift::Types::STRING, :name => 'estauts'},
    LADOCULPABLE => {:type => ::Thrift::Types::STRING, :name => 'ladoCulpable'},
    IMPLICADOS => {:type => ::Thrift::Types::LIST, :name => 'implicados', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Vehiculo}}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field idReporte is unset!') unless @idReporte
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field latitud is unset!') unless @latitud
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field longitud is unset!') unless @longitud
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field estauts is unset!') unless @estauts
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field ladoCulpable is unset!') unless @ladoCulpable
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field implicados is unset!') unless @implicados
  end

  ::Thrift::Struct.generate_accessors self
end

class Usuario
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDUSUARIO = 1
  NOMBRE = 2
  ROL = 3
  USUARIO = 4
  PASSWORD = 5

  FIELDS = {
    IDUSUARIO => {:type => ::Thrift::Types::I32, :name => 'idUsuario'},
    NOMBRE => {:type => ::Thrift::Types::STRING, :name => 'nombre'},
    ROL => {:type => ::Thrift::Types::I32, :name => 'rol'},
    USUARIO => {:type => ::Thrift::Types::STRING, :name => 'usuario'},
    PASSWORD => {:type => ::Thrift::Types::STRING, :name => 'password'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field idUsuario is unset!') unless @idUsuario
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field nombre is unset!') unless @nombre
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field rol is unset!') unless @rol
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field usuario is unset!') unless @usuario
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field password is unset!') unless @password
  end

  ::Thrift::Struct.generate_accessors self
end

class Vehiculo
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDVEHICULO = 1
  MARCA = 2
  MODELO = 3
  YEAR = 4
  COLOR = 5
  NUMPLACAS = 6
  NOMBRECONDUCTOR = 7

  FIELDS = {
    IDVEHICULO => {:type => ::Thrift::Types::I32, :name => 'idVehiculo'},
    MARCA => {:type => ::Thrift::Types::STRING, :name => 'marca'},
    MODELO => {:type => ::Thrift::Types::STRING, :name => 'modelo'},
    YEAR => {:type => ::Thrift::Types::I32, :name => 'year'},
    COLOR => {:type => ::Thrift::Types::STRING, :name => 'color'},
    NUMPLACAS => {:type => ::Thrift::Types::STRING, :name => 'numPlacas'},
    NOMBRECONDUCTOR => {:type => ::Thrift::Types::STRING, :name => 'nombreConductor'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field idVehiculo is unset!') unless @idVehiculo
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field marca is unset!') unless @marca
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field modelo is unset!') unless @modelo
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field year is unset!') unless @year
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field color is unset!') unless @color
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field numPlacas is unset!') unless @numPlacas
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field nombreConductor is unset!') unless @nombreConductor
  end

  ::Thrift::Struct.generate_accessors self
end

class Error < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ERRORCODE = 1
  MENSAJE = 2

  FIELDS = {
    ERRORCODE => {:type => ::Thrift::Types::I32, :name => 'errorCode'},
    MENSAJE => {:type => ::Thrift::Types::STRING, :name => 'mensaje'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field errorCode is unset!') unless @errorCode
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field mensaje is unset!') unless @mensaje
  end

  ::Thrift::Struct.generate_accessors self
end

