#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'freway_types'

module IniciarSesion
  class Client
    include ::Thrift::Client

    def iniciarSesion(email, password)
      send_iniciarSesion(email, password)
      return recv_iniciarSesion()
    end

    def send_iniciarSesion(email, password)
      send_message('iniciarSesion', IniciarSesion_args, :email => email, :password => password)
    end

    def recv_iniciarSesion()
      result = receive_message(IniciarSesion_result)
      return result.success unless result.success.nil?
      raise result.exp unless result.exp.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'iniciarSesion failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_iniciarSesion(seqid, iprot, oprot)
      args = read_args(iprot, IniciarSesion_args)
      result = IniciarSesion_result.new()
      begin
        result.success = @handler.iniciarSesion(args.email, args.password)
      rescue ::Error => exp
        result.exp = exp
      end
      write_result(result, oprot, 'iniciarSesion', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class IniciarSesion_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    EMAIL = 1
    PASSWORD = 2

    FIELDS = {
      EMAIL => {:type => ::Thrift::Types::STRING, :name => 'email'},
      PASSWORD => {:type => ::Thrift::Types::STRING, :name => 'password'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class IniciarSesion_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    EXP = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::Usuario},
      EXP => {:type => ::Thrift::Types::STRUCT, :name => 'exp', :class => ::Error}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

