#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'freway_types'

module RegistrarUsuario
  class Client
    include ::Thrift::Client

    def registrarUsuario(usuario)
      send_registrarUsuario(usuario)
      return recv_registrarUsuario()
    end

    def send_registrarUsuario(usuario)
      send_message('registrarUsuario', RegistrarUsuario_args, :usuario => usuario)
    end

    def recv_registrarUsuario()
      result = receive_message(RegistrarUsuario_result)
      return result.success unless result.success.nil?
      raise result.exp unless result.exp.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'registrarUsuario failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_registrarUsuario(seqid, iprot, oprot)
      args = read_args(iprot, RegistrarUsuario_args)
      result = RegistrarUsuario_result.new()
      begin
        result.success = @handler.registrarUsuario(args.usuario)
      rescue ::Error => exp
        result.exp = exp
      end
      write_result(result, oprot, 'registrarUsuario', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class RegistrarUsuario_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    USUARIO = 1

    FIELDS = {
      USUARIO => {:type => ::Thrift::Types::STRUCT, :name => 'usuario', :class => ::Usuario}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class RegistrarUsuario_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    EXP = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::Respuesta},
      EXP => {:type => ::Thrift::Types::STRUCT, :name => 'exp', :class => ::Error}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

